version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: docu-verify-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sauparnika@2012
      POSTGRES_DB: docuverify
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docu-verify-api
    depends_on:
      - db
    ports:
      - "5200:8080"
      - "7200:8443"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=docuverify;Username=postgres;Password=Sauparnika@2012
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8443
    restart: always

volumes:
  pgdata:
